config/routes.rb
Rails.application.routes.draw do  

	match 'catalog/latest', :to => 'catalog#latest', via: [:get, :post]
 
 get 'catalog/index'

  get 'catalog/show'

  get 'catalog/search'

  get 'catalog/latest'

  resources :publishers

  namespace :admin do
    resources :books
	resources :author
	resources :publishers
  end
  namespace :admin do
  get 'author/new'
  end

  namespace :admin do
  get 'author/create'
  end

  namespace :admin do
  get 'author/edit'
  end

  namespace :admin do
  get 'author/update'
  end

  namespace :admin do
  get 'author/destroy'
  end

  namespace :admin do
  get 'author/show'
  end

  namespace :admin do
  get 'author/index'
  end

  get 'about/index'

  scope :module => "admin" do
resources :books
end

root :to => 'catalog#index'
match ':controller(/:action(/:id(.:format)))', via: [:get, :post]

end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
has_many :books
validates_length_of :name, :in => 2..255, :message => "lauks ir tukšs vai pārāk garš(2-255)!"
validates_uniqueness_of :name, :message => "ar šādu vērtību eksistē!"
attr_accessible :name
end

app/controllers/admin/publishers_controller.rb
class Admin::PublishersController < ApplicationController
  before_action :set_publisher, only: [:show, :edit, :update, :destroy]

  # GET /publishers
  # GET /publishers.json
  def index
    @publishers = Publisher.all
  end

  # GET /publishers/1
  # GET /publishers/1.json
  def show
  @publisher = Publisher.find(params[:id])
@page_title = @publisher.name
respond_to do |format|
format.html # show.html.erb
format.json { render json: @publisher }
end
  end

  # GET /publishers/new
  def new
    @publisher = Publisher.new
  end

  # GET /publishers/1/edit
  def edit
  end

  # POST /publishers
  # POST /publishers.json
  def create
@publisher = Publisher.new(params[:publisher])
respond_to do |format|
if @publisher.save
format.html { redirect_to([:admin, @publisher],
:notice => 'Firma veiksmīgi pievienota.') }
format.json { render json: @publisher, status: :created,
location: @publisher }
else
format.html { render :action => "new" }
format.json { render json: @publisher.errors,
status: :unprocessable_entity }
end
end
end

  # PATCH/PUT /publishers/1
  # PATCH/PUT /publishers/1.json
  def update
@publisher = Publisher.find(params[:id])
respond_to do |format|
if @publisher.update_attributes(params[:publisher])
format.html { redirect_to([:admin, @publisher],
:notice => 'Firma veiksmīgi atjaunota.') }
format.json { head :no_content }
else
format.html { render :action => "edit" }
format.json { render json: @publisher.errors,
:status => :unprocessable_entity }
end
end
end

  # DELETE /publishers/1
  # DELETE /publishers/1.json
  def destroy
@publisher = Publisher.find(params[:id])
@publisher.destroy
respond_to do |format|
format.html { redirect_to(admin_publishers_url) }
format.json { head :no_content }
end
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publisher
      @publisher = Publisher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def publisher_params
      params.require(:publisher).permit(:name)
    end
end

app/helpers/admin/publishers_helper.rb
module Admin::PublishersHelper
end

app/views/admin/publishers/edit.html.erb
<h1>Firmas rediģēšana</h1>

<%= render 'form' %>

<%= link_to 'Parādīt', :action => 'show', :id => @publisher %> |
<%= link_to 'Atpakaļ', admin_publishers_path %>

app/views/admin/publishers/index.html.erb
<h1>Firmu saraksts</h1>
<table>
<tr>
<th>Nosaukums</th>
<th></th>
<th></th>
<th></th>
</tr>
<% @publishers.each do |publisher| %>
<tr>
<td><%= publisher.name %></td>
<td><%= link_to 'Parādīt', :action => 'show', :id => publisher %></td>
<td><%= link_to 'Rediģēt', :action => 'edit', :id => publisher %></td>
<td><%= button_to 'Dzēst!', {:action => 'destroy', :id => publisher}, method: :delete, data: {confirm: "Vai esat pārliecināts??"} %></td>
</tr>
<% end %>
</table>
<br />
<%= link_to 'Jauna firma', :action => 'new' %>

app/views/admin/publishers/new.html.erb
<h1>Jauna Firma</h1>

<%= render 'form' %>

<%= link_to 'Atpakaļ', admin_publishers_path %>

app/views/admin/publishers/show.html.erb
<dl>
<dt>Nosaukums</dt>
<dd><%= @publisher.name %></dd>
</dl>
<%= link_to 'Rediģēt', :action => 'edit', :id => @publisher %> |
<%= link_to 'Atpakaļ', admin_publishers_path %>